### ISSUE TITLE
Unable to change note type once added

### ISSUE THREAD

**Issue by jarofghosts** [outline/rich-markdown-editor#256] opened 2020-08-27 17:06 UTC
When using the editor, after inserting a note (info, warning, tip) a dropdown on the right seems to present the option to change the note type. Selecting a different note type, however, does nothing and is immediately reverted to the original type.

**To Reproduce**
1. Insert a note in the editor
2. Click on the dropdown on the right of the inserted note
3. Select a different note type from the original
4. See the type does not update

**Expected behavior**
I would expect the note type to change to the type I selected

**Version**
10.6.2

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: chrome
 - Version: 84.0.4147.135

**Comment by jarofghosts** [comment] 2020-08-27 21:17
Just noticed I have the same issue trying to update the code language selection for code blocks

**Comment by tommoor** [comment] 2020-08-28 00:53
Can you reproduce this in the included example? I currently cannot – last time there was an odd issue like this it's because some dependency had created an incompatibility in a patch release. So perhaps try installing with `yarn install --pure-lockfile`

**Comment by jarofghosts** [comment] 2020-08-28 04:34
I reproduced this on the instance live on getoutline, but won't be able to try with the example code until some time tomorrow.

**Comment by tommoor** [comment] 2020-08-28 05:00
You might need to leave a GIF or something as we're both on macOS / Chrome 84 the behavior should be identical 😢

**Comment by jarofghosts** [comment] 2020-08-28 16:34
![Kapture 2020-08-28 at 09 31 58](https://user-images.githubusercontent.com/1013892/91591281-88f9a780-e911-11ea-8698-53ef1f102311.gif)

**Comment by tommoor** [comment] 2020-08-30 18:40
Can you add a breakpoint in the click handler?
Are there any errors in the console? 
We need to find out how far the event is getting before being dropped…

**Comment by jl-gogovapps** [comment] 2020-10-13 19:12
I _think_ I'm seeing an issue here that could be related, but the symptom is a little different:

![Kapture 2020-10-13 at 12 52 17](https://user-images.githubusercontent.com/44532602/95905213-8ee30500-0d66-11eb-8661-c83fb19c0365.gif)

**Comment by tommoor** [comment] 2020-10-21 06:54
Based on other similar reports and inability to repro I'm closing this out as a duplicate of the issue where the incorrect version of `prosemirror-transform` is installed…

https://github.com/outline/rich-markdown-editor/issues/261#issuecomment-686201757

**Closed by tommoor** 2020-10-21 06:54 UTC
Labels: bug, more-information-needed
