### ISSUE TITLE
crash when delete last character of link

### ISSUE THREAD

**Issue by hecor** [outline/rich-markdown-editor#73] opened 2019-03-22 06:03 UTC
![image](https://user-images.githubusercontent.com/1171710/54803550-e6b0ab80-4caa-11e9-8360-f33e9782cab5.png)
![image](https://user-images.githubusercontent.com/1171710/54803564-f3cd9a80-4caa-11e9-8e1b-38763819164f.png)

![image](https://user-images.githubusercontent.com/1171710/54803578-09db5b00-4cab-11e9-9181-80c2c039f8a7.png)

![image](https://user-images.githubusercontent.com/1171710/54803632-355e4580-4cab-11e9-8e2a-764d116edda7.png)

**Also when select the whole line and click link ToolbarButton, crash too.**

![image](https://user-images.githubusercontent.com/1171710/54807232-8ecc7180-4cb7-11e9-8dc9-1dd95fc27a40.png)

![image](https://user-images.githubusercontent.com/1171710/54807122-309f8e80-4cb7-11e9-8c27-a64ac3d6cac6.png)

Thanks!

**Comment by tommoor** [comment] 2019-03-24 13:56
This seems to be the underlying issue in Slate: 
https://github.com/ianstormtaylor/slate/issues/2319

**Comment by tommoor** [comment] 2019-04-10 02:39
Hey @hecor – are you still able to reproduce this? I've been unable to on the latest build – I think it was fixed by the most recent Slate upgrade. Please reopen if you can, closing for now.

**Closed by tommoor** 2019-04-10 02:39 UTC
Labels: bug

**Comment by hecor** [comment] 2019-04-10 14:57
Hi @tommoor , the first bug still happen every time, you can check it on www.getoutline.com
The second one seems to disappear.

**Comment by hecor** [comment] 2019-04-11 14:56
@tommoor Thanks for the fix, the crash don't happen now, but the delete behavior still not quite right.

![editor-delete-bug](https://user-images.githubusercontent.com/1171710/55967373-caea6500-5cac-11e9-80dc-b0325722c7be.gif)

after delete the last character of link, if I press delete again, it will delete a blank line and a character of last paragraph.

**Comment by tommoor** [comment] 2019-04-11 15:49
Ah yes, I spotted this too! I think fixing the crash exposed this always existing bug rather than creating it – will try and track down what's happening here

**Comment by vnugent** [comment] 2019-04-12 11:24
I can confirm this issue in v0.45.0 and `@mercuriya/slate-linkify` plugin.  Slate will crash when deleting last character of a link.

**Comment by hecor** [comment] 2019-04-15 10:25
> Ah yes, I spotted this too! I think fixing the crash exposed this always existing bug rather than creating it – will try and track down what's happening here

Ok, thanks a lot.
