### ISSUE TITLE
Module not found:  Can't resolve 'immutable'

### ISSUE THREAD

**Issue by jacargentina** [outline/rich-markdown-editor#122] opened 2019-11-08 14:43 UTC
Trying to use this module for the first time, i'm  getting this:
```bash
Failed to compile.

 ./node_modules/@domoinc/slate-edit-table/lib/index.es.js
Module not found: Can't resolve 'immutable' in '/home/user/git/web-site/node_modules/@domoinc/slate-edit-table/lib' 
```

**Comment by focux** [comment] 2019-11-13 05:06
I'm experiencing the same issue using NextJS.

**Comment by tommoor** [comment] 2019-11-13 16:17
@focux the example you linked works fine? I'm also unable to reproduce this with a fresh clone and install locally. I suspect it's somehow related to there being different versions of Immutable installed in your project.

**Comment by focux** [comment] 2019-11-13 18:51
@tommoor  Actually, I was able to fix it by installing immutable locally, otherwise, it won't work.

**Comment by tommoor** [comment] 2019-11-13 18:52
Weird, the dependency is clearly defined 🤷‍♂ 

https://github.com/outline/rich-markdown-editor/blob/master/yarn.lock#L3493-L3496

**Comment by jacargentina** [comment] 2019-11-13 19:00
@tommoor I'm trying to use `rich-markdown-editor` as a dependency on my own project, which uses `npm` for installing; maybe that causes this problem?

**Comment by tommoor** [comment] 2019-11-13 19:05
Could be, in that case it wouldn't respect the yarn.lock so the version it installs might be different – it should certainly still get installed though.

**Comment by jacargentina** [comment] 2019-11-13 19:21
@tommoor this clue can direct you on how to solve it

`immutable` dep is listed on `devDependencies` (not ` dependencies`) on the ` package.json` file.

**Comment by tommoor** [comment] 2019-12-05 03:47
But it should be dev only 🤔 – this module doesn't directly depend on `immutable` in production, only sub-dependencies do.

**Comment by alexlouden** [comment] 2020-01-23 01:34
I just saw this too, adding `"immutable": "3.8.2"` to my devDependencies fixed it for me :)

**Comment by cofinley** [comment] 2020-02-28 17:04
> 
> 
> I just saw this too, adding `"immutable": "3.8.2"` to my devDependencies fixed it for me :)

Thanks, fixed with `npm install immutable --save-dev`.

**Comment by tommoor** [comment] 2020-05-07 04:06
Thanks for filing. As of v10 the editor has been re-written in Prosemirror, so this issue is no longer applicable.

**Closed by tommoor** 2020-05-07 04:06 UTC

**Comment by hamidmallhi** [comment] 2021-07-19 14:51
Thanks, fixed with npm install immutable --save-dev.
