### ISSUE TITLE
defaultValue that comes async is not rendered

### ISSUE THREAD

**Issue by sklinov** [outline/rich-markdown-editor#379] opened 2021-02-06 09:03 UTC
**To Reproduce**
1. Go to [Sandbox](https://codesandbox.io/s/rich-markdown-editor-kbbyu?file=/src/App.tsx)
2. See that placeholder is not changed after `defaultValue` comes in async
3. You can check out the console, to see, that it's getting changed from `undefined` to `string`

**Expected behavior**
Set `<Editor >` value to `defaultValue` that came async if editing has not started yet.

**Version**
11.1.6

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![image](https://user-images.githubusercontent.com/38185977/107113865-8a95a700-6883-11eb-9c2b-10f81626f7d5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome @latest , Firefox Developer Edition

**Comment by tommoor** [comment] 2021-02-06 17:34
Hey @sklinov, this is by design – defaultValue is only evaluated on mount, this should be the same behavior as passing `defaultValue` to any input type in React?

**Comment by tommoor** [comment] 2021-02-07 19:40
Closing as by design, you should delay rendering the editor with a loading state until `defaultValue` is available

**Closed by tommoor** 2021-02-07 19:40 UTC
Labels: bug
