### ISSUE TITLE
Markdown is not properly interpreted when doing a copy/paste.

### ISSUE THREAD

**Issue by mattcollier** [outline/rich-markdown-editor#330] opened 2020-11-25 15:34 UTC
Markdown is not properly interpreted when doing a copy/paste.

**To Reproduce**
1. Copy the raw markdown from this gist: https://gist.githubusercontent.com/mattcollier/85ac901276c8610ad57d30b8efc80b75/raw/6577c3ea34f089ce1fd3fb170e28311424f87a0b/some.md
2. Create a new document on getoutline.com
3. Paste the raw markdown into the new document

**Expected behavior**
Markdown should be properly interpreted, see screenshot

**Version**
current code on getoutline.com

**Screenshots**
![Screenshot from 2020-11-25 10-31-20](https://user-images.githubusercontent.com/902041/100248440-793a3100-2f09-11eb-97b3-d2e15ba5f315.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 86.0.4240.198

**Comment by tommoor** [comment] 2020-12-07 04:08
Could you try pasting with CMD+Shift+V? I think it depends on where the paste is happening from – and if the clipboard contains html then the paste logic currently prefers that.

**Comment by tommoor** [comment] 2020-12-12 22:30
Hey @mattcollier I'm closing this out as expected behavior when pasting HTML, as mentioned above if you paste plain text all will be good.

**Closed by tommoor** 2020-12-12 22:30 UTC
Labels: bug

**Comment by mattcollier** [comment] 2020-12-12 22:44
@tommoor I just tried this again and ctrl+shift+v on Linux (Chrome 87.0.4280.88, Gnome on Ubuntu 20.04) does not get interpreted as markdown.  Here is another trivial example which is really no different from the OP.  

Again, I'm creating a new document, copying the RAW markdown from the gist, and it is being interpreted as plaintext where the `###` is not being detected as a column heading.  Other platforms require the use of a right-click menu for "Paste special" to signal to the editor that the pasted input should be processed as markdown vs plaintext.

https://gist.githubusercontent.com/mattcollier/4639e2b4239cba29bc0dc310fae0c1ed/raw/3ef3c57105b4b902f7c03aabb8ecbb8e9a31135b/gistfile1.md

**Comment by tommoor** [comment] 2020-12-13 06:37
ctrl+shift+v is probably a macOS thing, I'm not sure what paste as plain text is on linux. The example is the same because you're copying from a html document so there's a `<pre>` tag in the html on the clipboard I'm afraid.

Trying to think how this could be changed, but without dropping support for pasting html it would be tricky…
